### ISSUE TITLE
how to run lure build in ci

### ISSUE THREAD

**Issue by gnuhub** [Elara6331/lure#61]
lure build 
-->Would you like to view the build script for

-->Would you still like to continue

how to use lure in ci without questions?

**Comment by Arsen6331** [comment]
I'll need to add a `-y` flag to bypass the questions, forgot about that. Thanks.

**Comment by Arsen6331** [comment]
I've just added the `--interactive` flag in the latest commit. It can be used like so: `lure --interactive=false build`. LURE will automatically detect if the input is a terminal too, so most likely you won't even need the flag. Try it without first.
