### ISSUE TITLE
error: lure_cache_manifest: file exists"

### ISSUE THREAD

**Issue by xpamych** [Elara6331/lure#63]
![image](https://user-images.githubusercontent.com/16473797/220272703-9b4f53f2-1959-4fa2-a45d-a3d843327f6d.png)

**Comment by Arsen6331** [comment]
Interesting, that shouldn't be possible. What happens if you try deleting `~/.cache/lure/pkgs/` or running `lure fix`?

**Comment by xpamych** [comment]
![image](https://user-images.githubusercontent.com/16473797/221493523-4d1a4ca2-8dfc-4ce4-b07b-358aee9abea6.png)

**Comment by Arsen6331** [comment]
That's weird. It seems to be working for me:

![image](https://user-images.githubusercontent.com/41810442/221691362-b0cd52bd-51cb-459f-8fb9-19554cd3f376.png)

Can you try the latest commit?

**Comment by xpamych** [comment]
straight trouble of some kind)
![image](https://user-images.githubusercontent.com/16473797/222402678-e70ca279-d634-4647-96d8-5b01996f6c69.png)
![image](https://user-images.githubusercontent.com/16473797/222402956-43de6f7c-7f92-40c5-b5a3-339c29f3448c.png)

**Comment by Elara6331** [comment]
Can you try this again? The issue you were having with installing `lure-git` has been fixed.

**Comment by Elara6331** [comment]
Please reopen the issue if this is still happening
