### ISSUE TITLE
Search, view description and install LURE package using fzf

### ISSUE THREAD

**Issue by berligostr** [Elara6331/lure#66]
I think a very convenient integration of the search and installation of the LURE package using the capabilities of fzf will come in handy:
lure ls 2>/dev/null | fzf -m --delimiter="[/ ]" --with-nth=2 --reverse --preview "lure info {2} 2>/dev/null" --preview-window right:60%:wrap | xargs -ro lure in

**Comment by berligostr** [comment]
> That `fzf` command won't work because you need to trim out the repo and version number before giving it to LURE, but it could work with some manipulation. However, if you do `lure in %`, it should give you something very similar

please check before you write comments. I took all this into account in this script

**Comment by Arsen6331** [comment]
I did, I ran it, it didn't work

**Comment by Arsen6331** [comment]
I then tried using `echo` to check what command it ran, and I got `lure in default/admc-git 3580.5a24f61`, which is incorrect.

**Comment by berligostr** [comment]
> I did, I ran it, it didn't work

[https://imgur.com/9NQGQ9p.png](url)

**Comment by Arsen6331** [comment]
Yeah, the window shows up and looks exactly like that, but if you select an option, you get an error, because LURE does not accept repo names and versions on the command line.

**Comment by berligostr** [comment]
> I then tried using `echo` to check what command it ran, and I got `lure in default/admc-git 3580.5a24f61`, which is incorrect.

you copied something incorrectly, because the --delimiter='[/ ]' parameter allows you to separate tabs, and lure info {2} selects exactly the package name without the repository and version. try replacing the single ' bows with double ' ones

**Comment by Arsen6331** [comment]
https://user-images.githubusercontent.com/41810442/221948220-9cc65d31-7d89-4264-8c0a-95668849261d.mp4

**Comment by Arsen6331** [comment]
Here's a working version of your command: 
```
lure ls 2>/dev/null | fzf -m --delimiter="[/ ]" --with-nth=2 --reverse --preview "lure info {2} 2>/dev/null" --preview-window right:60%:wrap | cut -f2 -d '/' | cut -f1 -d ' ' | xargs -ro lure in
```

However, if I was to implement this, I'd want to avoid `fzf` as a dependency, so I'd probably end up implementing it using the bubbletea library.

**Comment by berligostr** [comment]
> Here's a working version of your command:
> 
> ```
> lure ls 2>/dev/null | fzf -m --delimiter="[/ ]" --with-nth=2 --reverse --preview "lure info {2} 2>/dev/null" --preview-window right:60%:wrap | cut -f2 -d '/' | cut -f1 -d ' ' | xargs -ro lure in
> ```
> 
> However, if I was to implement this, I'd want to avoid `fzf` as a dependency, so I'd probably end up implementing it using the bubbletea library.

I checked on the team:
lure ls 2>/dev/null | fzf -m --delimiter='[/ ]' --with-nth=2 --reverse --preview "lure info {2} 2>/dev/null" --preview-window right:60%:wrap | awk -F'[/ ]' '{ print $2 }' | xargs -ro echo

and fixed, working version:
lure ls 2>/dev/null | fzf -m --delimiter='[/ ]' --with-nth=2 --reverse --preview "lure info {2} 2>/dev/null" --preview-window right:60%:wrap | awk -F'[/ ]' '{ print $2 }' | xargs -ro lure in
