### ISSUE TITLE
Version when switching branches.

### ISSUE THREAD

**Issue by xpamych** [Elara6331/lure#68]
I wanted to make an installer for the dev-git version, but the version function seems to write something extra to the package version when switching branches.
![Screenshot_20230402_144147](https://user-images.githubusercontent.com/16473797/229350588-31cdd913-92b4-458a-a2f9-18ff2fcb9645.png)
![Screenshot_20230402_144212](https://user-images.githubusercontent.com/16473797/229350636-0e6c7b80-6701-4f16-9642-e7afbd79eafe.png)

**Comment by Elara6331** [comment]
You shouldn't checkout the dev branch inside a function. Instead, use the `~rev` parameter like so:

```bash
sources=("git+https://gitflic.ru/project/plemyakh/hln-a.git?~rev=dev")
```

Anything that gets returned from the `version()` function will be added to the updated version.
