### ISSUE TITLE
Warning printed as go type rathor then text

### ISSUE THREAD

**Issue by godalming123** [Elara6331/lure#69]
When I run lure list on fedora for the first time I get the message:
```
{"msg":"Database version does not exist. Run lure fix if something isn't working.","level":"warn"}
```
This is a go type and it should be formatted as a string eg the message above but with yellow text because it is a warning and no curly braces, it also does not print a newline after printing this go type so, on the same line you then get the text:
```
--> Pulling repository name="default"
```
directly afterwords.

**Comment by Elara6331** [comment]
That's not a Go type, it's JSON. This is happening because the database was being loaded before the logger was initialized. It should be fixed in da31b862a2bcc66385853a7d03798813188c7cff. Thanks.
