### ISSUE TITLE
How do you test lure.sh files locally?

### ISSUE THREAD

**Issue by godalming123** [Elara6331/lure#70]
Their is a file in the docs about how to add packages to the lure repo but how are we meant to test them before we submit them as a PR? Maybe you could add a option for local repos where you specify a folder on your computer and then use that as a repo for testing purposes before you create a pull request. Just a thought.

**Comment by SinTan1729** [comment]
Not the author, but I test my LURE packages by using `lure build`. It will build the `lure.sh` file present in the current directory and create a package based on the distro. You should then be look inside the package to see if it's built as intended. Also, you can go ahead and install the packages using your distro's package manager if you wanna test them out.

**Comment by godalming123** [comment]
I have added a PR (https://github.com/Elara6331/lure/pull/72) which will make this discoverable

**Comment by godalming123** [comment]
My PR has been merged thanks for the help
