### ISSUE TITLE
Ability to switch branches in sources

### ISSUE THREAD

**Issue by ErikReider** [Elara6331/lure#71]
In a PKGBUILD, I'd normally be able to switch branches through a fragment (ex: `git+https://github.com/Username/repo.git#branch=some_branch_name`) but it doesn't seem like Lure supports this unless I'm mistaken?

**Comment by Elara6331** [comment]
You should be able to do that with the `~rev` parameter mentioned [here](https://github.com/Elara6331/lure/blob/master/docs/packages/build-scripts.md#sources). It would look something like `git+https://github.com/Username/repo.git?~rev=some_branch_name`

**Comment by ErikReider** [comment]
Hmm. Doesn't seem to work, I'm getting `Error building package error="reference not found"`

**Comment by Elara6331** [comment]
LURE wasn't fetching all the remote references. Fixed in e3838621a9f0be37bb6a217f0c1bfb6db89b7189. Can you please test it?

**Comment by ErikReider** [comment]
Works now, thanks! :)

**Comment by ErikReider** [comment]
Should also fix #68 right?

**Comment by Elara6331** [comment]
> Should also fix #68 right? The version number was updated on my script

No, the problem there seems to be that they put a `git checkout` command in the version function and its output got placed in the version. They just need to use the `~rev` parameter and that should fix their problem.
