### ISSUE TITLE
Error parsing system language on WSL Ubuntu

### ISSUE THREAD

**Issue by atirut-w** [Elara6331/lure#75]
Error:
```
{"msg":"Error parsing system language","level":"fatal","error":"language: tag is not well-formed"}
```

Can be worked around by setting `LANG` to `en_us`

**Comment by Elara6331** [comment]
What is `$LANG` set to by default on your system?

**Comment by atirut-w** [comment]
`C.UTF-8`

**Comment by Elara6331** [comment]
That issue has been fixed but the fix isn't in any release yet. The latest commit should work. I will be making a new release soon if you'd rather wait for that.

**Comment by atirut-w** [comment]
Doesn't seem to be in the repo yet :/
![image](https://github.com/Elara6331/lure/assets/25323231/3d447822-f1c6-47b5-9198-c46a1036965d)

**Comment by Elara6331** [comment]
You're right, sorry. Should be there now :)

**Comment by atirut-w** [comment]
Confirmed as fixed
