### ISSUE TITLE
Ability to use `local` as a source

### ISSUE THREAD

**Issue by zocker-160** [Elara6331/lure#80]
I am currently trying to use a local file / folder as a source, but it does not work `unsupported protocol scheme "local"` so I guess this is not supported.

**Use Case**

There is a niche use case for this in order to be able to package applications which are not publicly available (behind login wall or paywall).

One such application is Aseprite, where the [AUR package of it](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aseprite-bin#n26) uses `local://` as a source in order to use a locally placed file.

Would it be possible to add that functionality?

**Comment by Elara6331** [comment]
Sure, I can add that! It shouldn't be too difficult.

**Comment by Elara6331** [comment]
Done in 383b886 :). Sorry it took so long. Just use `local:///file.ext` (three slashes).

**Comment by zocker-160** [comment]
No worries, thank you! :heart:
