### ISSUE TITLE
Add optdeps in scriptinstall

### ISSUE THREAD

**Issue by xpamych** [Elara6331/lure#81]
Some packages have dependencies that are needed only under certain conditions. For example libappindicator-gtk3, which is required only when using Gnome. Is it possible to add optdeps?

**Comment by Elara6331** [comment]
I just added this in the latest commit: https://github.com/Elara6331/lure/blob/master/docs/packages/build-scripts.md#opt_deps

**Comment by Elara6331** [comment]
Fixed in 8dbdd3e
